/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.doris.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2024-05-20")
public enum TWorkloadActionType implements org.apache.thrift.TEnum {
  MOVE_QUERY_TO_GROUP(0),
  CANCEL_QUERY(1);

  private final int value;

  private TWorkloadActionType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TWorkloadActionType findByValue(int value) { 
    switch (value) {
      case 0:
        return MOVE_QUERY_TO_GROUP;
      case 1:
        return CANCEL_QUERY;
      default:
        return null;
    }
  }
}
